ALTER TABLE sakhi_clinic_room_categories ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE sakhi_clinic_rooms ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE sakhi_clinic_beds ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
